version: '3.8'

services:
  # The backend application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: dog_pedigree_development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DIALECT: postgres
      JWT_SECRET: your-super-secret-key-change-in-production
      JWT_EXPIRATION: 1d
    # Comment out volumes for now to prevent overriding built files
    # volumes:
    #   - ./:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: unless-stopped

  # The PostgreSQL database
  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dog_pedigree_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    
  # pgAdmin for PostgreSQL database management
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
